In [1]:
import numpy as np

#### Scalars
Define scalars here

In [20]:
s = np.array(5)
print(s)

5


In [21]:
s.shape

()

In [ ]:
sum = s+3
print(sum)

#### Vectors

In [23]:
V= np.array([1,2,3])
print(V)

[1 2 3]


In [24]:
V.shape

(3,)

In [25]:
V[1]

2

#### Matrices

In [26]:
M= np.array([[1,2,3]]) #[4,5,6], [7,8,9]])
print(M)

[[1 2 3]]


In [27]:
M.shape

(1, 3)

#### Tensors

In [28]:
T= np.array([[[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]]])
print(T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [29]:
x=V.reshape(1,3)
print(x)
print('\n',V.reshape(3,1))

[[1 2 3]]

 [[1]
 [2]
 [3]]


### Matrix Operations

In [56]:
values = np.array([1,2,3,4,5])
print(values)

[1 2 3 4 5]


In [57]:
values = values+5
print(values)

[ 6  7  8  9 10]


In [58]:
values -=5

In [59]:
print(values)

[1 2 3 4 5]


### Matrix Multiplication

In [34]:
a= np.array([[1,2,3,4], [1,2,2,1]]) #
print(a)

[[1 2 3 4]
 [1 2 2 1]]


In [35]:
print(a.T) #Transpose

[[1 1]
 [2 2]
 [3 2]
 [4 1]]


In [36]:
b= (a.T) + 2
print(b)

[[3 3]
 [4 4]
 [5 4]
 [6 3]]


In [37]:
mul= np.matmul(a,b)
print(mul)

[[50 35]
 [27 22]]


In [38]:
print(np.matmul(mul,mul))

[[3445 2520]
 [1944 1429]]


### Matrix Transpose Use

In [39]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
                    [0.04, -0.003, 0.025, 0.009], \
                    [0.012, -0.045, 0.28, -0.067]])
bias = np.array([1,2,5,2])

In [40]:
print('Shape of Input - X is ', inputs.shape)

Shape of Input - X is  (1, 4)


In [41]:
print('Shape of Weights (W) is ', weights.shape)

Shape of Weights (W) is  (3, 4)


Y= WX +b <br>
X - Input<br>
W - Weights<br>
b - Bias<br>

In [42]:
Y = np.matmul(inputs, weights.T)
print(Y)

[[-0.01299  0.00664  0.13494]]


In [43]:
Y.shape

(1, 3)

In [44]:
print(np.matmul(weights, inputs.T).T)

[[-0.01299  0.00664  0.13494]]


In [45]:
a

array([[1, 2, 3, 4],
       [1, 2, 2, 1]])

In [46]:
np.add(a,a)

array([[2, 4, 6, 8],
       [2, 4, 4, 2]])

In [47]:
np.subtract(a,a)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [48]:
np.divide(a,2)

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 0.5,  1. ,  1. ,  0.5]])

In [49]:
np.divide(a,a)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [50]:
np.divide(a,np.subtract(a,a))

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([[ inf,  inf,  inf,  inf],
       [ inf,  inf,  inf,  inf]])

In [51]:
np.multiply(a,4)

array([[ 4,  8, 12, 16],
       [ 4,  8,  8,  4]])